language: python
python:
- '3.6'
before_install:
    - python --version
    - pip install -U pip
install:
- pip install -r requirements.txt
script:
    python manage.py test
deploy:
    provider: heroku
    api_key:
        secure: "pdqs9nVn/7w1vCSTe0OQzPHjRJSt4U9YDAfp/iygaWtag8ux7o9P9YrrPBptjbrmtbJ0oXQ6XVqaPzTXK7Z/2Y4//kJjZ5Mjt52YiuKxPKkbX/CGciudI2OBQyep11KWHhw/HI+jd6US2AtgzqHJyeg7CRIHL7XaOIsUm4k44u5EtC9LPP7nCl6YaeEV4zt6WfYIsLCP/Yv3WBPTk3nCj744Za6bxjZj2JuXqmAtitIxyEJnLQqzPJ7Mk7t19B5Q4WRtlOl2Dc+OmQO4iTSSbsCuUOhdsgZGB6MnDSerIVEESn/lIRtYS3mJM/d7jSf/1yyNGn+zPmz2kYxiSgRrC/se9/5rEmraU56EPA5lWSnbPWax5hOM3DihFBK7Oc5WlGpTrJuGkgFbsUuxM5Q1c8XVEw895lpIhGdhkyb4nr6Rf4x7aQGoYgf/T6GqJxylqeLPlZqicZL6b/ousqqnYciGUDX2t473BnQeFbnm3ChSKbJ23XKPXy9/xwLI/YnyYIk/r+NLOS0wCoisA6qESdTiO9cIX7yK/3V/68AwaA4HyyVWqs8OwSKP6giMRHkiFN6Er/4RMTGBkoxHif3Pd8ARDFXvg1XVB7HPZ7qO2JISZu1YkAavLXk/av0m/jSzUzjhKYORi/NYOFG2ApF325NsYZii/V+lJNrr/56XH0g="
    app: primerx-dev
