language: python
python:
- '3.6'
before_install:
    - python --version
    - pip install -U pip
install:
- pip install -r requirements.txt
script:
    python manage.py test
deploy:
    provider: heroku
    api_key:
        secure: NEsaoHiU4HaYBGuhZm0J33l6TIYquWc9QdVl25MJ2ZUOmgCW7udhxwNxlSl4tJ5PZPIQs2ZSu7to7CmdR1kEu3JZFdKT28Pwu0ZdZOWTgctBUbHaSxZixvEwb3FZiGSMEgo4mE4smkh612qCFNXeco6tYUuf3CbpC/19KwmP0pZIpBuKa8YZo+hpPjg3Bw7nsZ0zHu5lhzlzoEAvJpTirVD8Dhk9L/h/sllsiD6TjU53LtoYlctbsyE2f3t4o3f7a6YfIOTOFkhw6hrcHK3ky9kZDhcLSS9OGuUezf2Biblyja+cxEAMUTuf1OtflXy2xicB3efKv781LcAGP8EbqiTw1r474i6rdXXN4rRQaOdWnYz53jsQiN2p0jyNtsLwwpCXu4vtQc4sdr21eesNCGp6DDXBjjN9w6EJj0dowj+TCxUGgvO/VbDvZ2Z6E4eml6AM6vel61Bm1mKEelgmb7jGn+B8e0JLZHqPqilQslLX/SN+aZadMP26X3aCniWEnfd7sA1fn245ICp89nHZ2bP2eQu7iySxeSko8m3ztnc2MJY1+c+dn4mu98vI59PG7C643JGbPsRDltLKOGnQDdIxLx14g1f+6TBmTkOK7PNWRNHKMzN/jiG9bdZDFy2GVdzRykls0AghrwpRjdROMaRprfe8PSlW7kJb2mhiWp4=
    app: primerx-dev
