version: '3'

env:
  NAME: primerdriver-dev
  SHORT_SHA:
    sh: git show --format="%h" --no-patch

tasks:
  test:
    cmds:
      - poetry run python -m unittest {{.CLI_ARGS}}

  build:
    cmds:
      - poetry run pyinstaller --clean -F --name primerdriver setup.py
      - docker run -v "$(pwd)":/build --rm --env NAME={{.NAME}} --name primerdriver --workdir /build kvdomingo/py-cli-builder:latest
