version: '3'

env:
  NAME: primerdriver
  SHORT_SHA:
    sh: git show --format="%h" --no-patch

tasks:
  setup:
    cmds:
      - pip install pre-commit
      - pre-commit install
      - poetry install

  test:
    cmds:
      - poetry run coverage run -m pytest

  build:
    cmds:
      - poetry run pyinstaller --clean -F --name primerdriver setup.py
      - docker run -v "$(pwd)":/build --rm --env NAME={{.NAME}} --name primerdriver --workdir /build kvdomingo/py-cli-builder:latest

  build-docs:
    cmds:
      - rm -rf docsrc/source/generated
      - poetry run sphinx-build -b html docsrc/source docs
