version: '3'

env:
  NAME: primerdriver-dev
  SHORT_SHA:
    sh: git show --format="%h" --no-patch

tasks:
  default:
    cmds:
      - docker compose -p $NAME up -d --build --remove-orphans {{.CLI_ARGS}}

  logs:
    cmds:
      - docker compose -p $NAME logs --follow {{.CLI_ARGS}}

  make-builder:
    cmds:
      - docker build -t kvdomingo/primerdriver-makelinux:latest -f Dockerfile.build .

  publish-builder:
    cmds:
        - docker push kvdomingo/primerdriver-makelinux:latest

  build-linux:
    cmds:
      - docker run -v "$(pwd)":/primerdriver --rm --name primerdriver-makelinux kvdomingo/primerdriver-makelinux:latest

  build:
    cmds:
      - pyinstaller --clean -F --name primerdriver setup.py

  shutdown:
    cmds:
      - docker compose -p $NAME stop {{.CLI_ARGS}}

  restart:
    cmds:
      - docker compose -p $NAME restart {{.CLI_ARGS}}

  reload-proxy:
    cmds:
      - docker compose -p $NAME exec -- proxy nginx -s reload

  clean:
    cmds:
      - docker compose -p $NAME down -v --remove-orphans
