# Generated by Django 3.0.3 on 2020-02-24 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characterize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.TextField()),
                ('mut_type', models.CharField(max_length=3)),
                ('mismatch', models.IntegerField()),
            ],
        ),
    ]
