name: PrimerDriver API unit testing

on: [ push, pull_request ]

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python manage.py test pdcli
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUG: ${{ secrets.DEBUG }}
          ON_CI: ${{ secrets.ON_CI }}
          ON_HEROKU: ${{ secrets.ON_HEROKU }}

