name: Make docs

on:
  pull_request:
    types:
      - edited
      - ready_for_review
      - synchronize
  workflow_dispatch:

jobs:
  make-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Install dependencies
        run: |
          python -m pip install "poetry==1.3.2"
          poetry install

      - name: Make docs
        run: poetry run sphinx-build -b html docsrc/source docs

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update docs
