name: Run tests

on:
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        name: Setup Python ${{ matrix.python-version }}
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install "poetry==1.3.2"
          poetry install
      - name: Run tests
        run: poetry run coverage run -m pytest
      - name: Update code coverage badge
        run: poetry run coverage-badge -o coverage.svg -f
        if: ${{ matrix.python-version == 3.10 }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        if: ${{ matrix.python-version == 3.10 }}
        with:
          commit_message: Update code coverage badge
